export const bodySet = {
    harvester: {
        300: [WORK, WORK, CARRY, MOVE],
        550: [WORK, WORK, WORK, WORK, CARRY, MOVE, MOVE],
        800: [WORK, WORK, WORK, WORK, WORK, CARRY, MOVE, MOVE, MOVE],
        1300: [WORK, WORK, WORK, WORK, WORK, CARRY, MOVE, MOVE, MOVE],
        1800: [WORK, WORK, WORK, WORK, WORK, CARRY, MOVE, MOVE, MOVE],
        2300: [WORK, WORK, WORK, WORK, WORK, CARRY, MOVE, MOVE, MOVE],
        5600: [WORK, WORK, WORK, WORK, WORK, CARRY, MOVE, MOVE, MOVE],
        10000: [WORK, WORK, WORK, WORK, WORK, CARRY, MOVE, MOVE, MOVE]
    },
    builder: {
        300: [WORK, CARRY, MOVE],
        550: [WORK, WORK, CARRY, CARRY, MOVE, MOVE],
        800: [WORK, WORK, WORK, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE],
        1300: [
            WORK,
            WORK,
            WORK,
            WORK,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            MOVE,
            MOVE,
            MOVE,
            MOVE
        ],
        1800: [
            WORK,
            WORK,
            WORK,
            WORK,
            WORK,
            WORK,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE
        ],
        2300: [
            WORK,
            WORK,
            WORK,
            WORK,
            WORK,
            WORK,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE
        ],
        5600: [
            WORK,
            WORK,
            WORK,
            WORK,
            WORK,
            WORK,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE
        ],
        10000: [
            WORK,
            WORK,
            WORK,
            WORK,
            WORK,
            WORK,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE
        ]
    },
    carrier: {
        300: [CARRY, CARRY, MOVE],
        550: [CARRY, CARRY, CARRY, MOVE, MOVE],
        800: [CARRY, CARRY, CARRY, CARRY, MOVE, MOVE],
        1300: [CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE],
        1800: [
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            MOVE,
            MOVE,
            MOVE,
            MOVE
        ],
        2300: [
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE
        ],
        5600: Array(30)
            .fill(CARRY, 0, 20)
            .fill(MOVE, 20, 30),
        10000: Array(48)
            .fill(CARRY, 0, 32)
            .fill(MOVE, 32, 48)
    },
    upgrader: {
        300: [WORK, CARRY, MOVE],
        550: [WORK, CARRY, MOVE, WORK, CARRY, MOVE],
        800: [WORK, CARRY, MOVE, WORK, CARRY, MOVE, WORK, CARRY, MOVE],
        1300: [
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE
        ],
        1800: [
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE
        ],
        2300: [
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE
        ],
        5600: [
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE
        ],
        10000: [
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE,
            WORK,
            CARRY,
            MOVE
        ]
    },
    reserver: {
        300: [MOVE, CLAIM],
        550: [MOVE, CLAIM],
        800: [TOUGH,MOVE, CLAIM],
        1300: [TOUGH,MOVE, CLAIM],
        1800: [TOUGH,MOVE, MOVE, CLAIM, CLAIM],
        2300: [TOUGH,MOVE, MOVE, CLAIM, CLAIM],
        5600: [TOUGH,MOVE, MOVE, CLAIM, CLAIM],
        10000: [TOUGH,MOVE, MOVE, CLAIM, CLAIM]
    },
    remoteMiner: {
        300: [TOUGH, WORK, CARRY, MOVE],
        550: [TOUGH, WORK, WORK, CARRY, CARRY, MOVE, MOVE],
        800: [TOUGH, WORK, WORK, WORK, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE],
        1300: [
            TOUGH,
            WORK,
            WORK,
            WORK,
            WORK,
            WORK,
            RANGED_ATTACK,
            CARRY,
            CARRY,
            CARRY,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE
        ],
        1800: [
            TOUGH,
            WORK,
            WORK,
            WORK,
            WORK,
            WORK,
            RANGED_ATTACK,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE
        ],
        2300: [
            TOUGH,
            WORK,
            WORK,
            WORK,
            WORK,
            WORK,
            RANGED_ATTACK,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE
        ],
        5600: [
            TOUGH,
            WORK,
            WORK,
            WORK,
            WORK,
            WORK,
            RANGED_ATTACK,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE
        ],
        10000: [
            TOUGH,
            WORK,
            WORK,
            WORK,
            WORK,
            WORK,
            RANGED_ATTACK,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE
        ]
    }
};
