name: Node.js CI

on: [push,workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [10.x]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2.1.3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Cache node_modules
              uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
              env:
                cache-name: cache-node-modules
              with:
                path: node_modules
                key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
            - name: test
              run: |
                echo "$CONFIG" > .screeps.json
                if [ !-f .screeps.json ];then
                exit 1
                fi
                npm install
                npm run test
            - name: update
              run: |
                echo "$CONFIG" > .screeps.json
                if [ !-f .screeps.json ];then
                exit 1
                fi
                npm install
                npm run once
              env:
                  CONFIG: ${{ secrets.config }}
